apiVersion: argoproj.io/v1alpha1
kind: Application

metadata:
  name: spring-app
  namespace: argocd

spec:
  project: default

  source:
    repoURL: 'https://github.com/akhilbeeraka598/akhil-practice.git'
    targetRevision: main
    path: Spring_booot/k8s

  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default

  syncPolicy:
    automated:
      prune: true
      selfHeal: true

